example/cmd/client/main.go
N/A
Attempting to run the included server and client examples resulted the following on the client side:
```bash
➭ ./client
2018/01/17 11:31:20 twirp error internal: failed to do request: Post localhost:8080/twirp/twitch.twirp.example.Haberdasher/MakeHat: unsupported protocol scheme "localhost"
```
Adding `http://` to the scheme fixes the issue.
```bash
➭ ./client
size:12 color:"black" name:"top hat"
```
=> Fixes unsupported protocol scheme "localhost" in client example

CONTRIBUTING.md
Adding content from the standard Amazon CONTRIBUTING file
=> Adding a note on CoC and contribution licensing to CONTRIBUTING

internal/twirptest/service_test.go
This is harmless, but it's an unecessary external dependency. We're for go1.7+, so we can safely require the standard library's context package.
=> Remove a stray golang.org/x/net/context import

internal/gen/typemap/typemap_test.go, internal/twirptest/service_test.go
Fixes #27.
Two changes are needed here:
First, I just removed our call to `t.Helper`, which is a minor convenience thing but only available in go1.9.
Second, I had to explicitly set the `ContentLength` of a `*http.Request` in a test that sends a truncated request body. I don't really know what changed here between go1.7 and go1.9, but *something* did, and in go1.7 the `http.Client` refuse to send the request because its body doesn't provide the number of bytes that the ContenLength field expects. This fixes that with a hammer.
=> Make tests pass in go1.7

clientcompat/internal/clientcompat/clientcompat.twirp.go, clientcompat/pycompat/clientcompat_pb2.py, example/service.twirp.go, example/service_pb2.py, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/multiple/multiple2_pb2.py, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer_pb2.py, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, internal/twirptest/service_pb2.py
Fixes #18.
This PR is a fresh run of `make`, with `protoc --version` `libprotoc 3.5.1`.  The Python changes are from the protoc upgrade and may not be desired.  The Go changes are from spelling fixes in Twirp's generator and should be synced up. Maybe CI could run `make` and check for changes to prevent drift in the future.
Happy to redo this with protoc 3.1 or 3.3 as required.
=> update generated files

clientcompat/internal/clientcompat/clientcompat.twirp.go, example/service.twirp.go, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/multiple/multiple2.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, protoc-gen-twirp/generator.go
This PR proposes a small change to generated Go clients. By replacing the `urlBase` field with a pre-computed array of service `urls`, service methods can do an array look-up instead of repetitive string concatenation, at the cost of more initialization in the constructor functions.
=> go-client: precompute service url strings

clientcompat/internal/clientcompat/clientcompat.twirp.go, example/service.twirp.go, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/multiple/multiple2.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, protoc-gen-twirp/generator.go
This PR proposes replacing the `generator.go` methods `generateProtobufClient` and `generateJSONClient` (which are nearly identical) with a parameterized `generateClient`.  The generated code remains functionally identical, but I aligned a few things (comments, `doProtoRequest()`->`doProtobufRequest()`) to keep the code simpler.
=> go-client: reduce repeated generator code

install_proto.bash, requirements.txt
#18 
This PR updates some protoc 3.1.0 and 3.3.0 references to 3.5.1, and extends Makefile/install_proto verification to that specific version as well. Here is example output from running `make` with the wrong version installed:
```sh
./install_proto.bash
/usr/local/bin/protoc
Protoc already installed
libprotoc 3.5.1 required, but found: libprotoc 3.3.0
Makefile:29: recipe for target 'setup' failed
make: *** [setup] Error 1
```
The happy path output remains the same.
=> protoc: update to 3.5.1 everywhere; verify from Makefile

README.md
As laid out in #61, I'd like to highlight these community-written generators.
I'd like an explicit okay from each person I'm linking to:
=> List third party generators on the README

docs/example.md
Fixes incorrect spelling of `package` in the client code example, as well as a couple of little client fixes.
=> fix typo in client example code

clientcompat/internal/clientcompat/clientcompat.twirp.go, context.go, example/service.twirp.go, internal/twirptest/client_test.go, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, protoc-gen-twirp/generator.go
fixes #81
Added Accept header to JSON and protobuf clients and ran make.
=> Set Accept header in generated client requests

clientcompat/pycompat/clientcompat_pb2_twirp.py, example/service_pb2_twirp.py, internal/twirptest/importable/importable_pb2_twirp.py, internal/twirptest/importer/importer_pb2_twirp.py, internal/twirptest/multiple/multiple1_pb2_twirp.py, internal/twirptest/multiple/multiple2_pb2_twirp.py, internal/twirptest/no_package_name/no_package_name_pb2_twirp.py, internal/twirptest/no_package_name_importer/no_package_name_importer_pb2_twirp.py, internal/twirptest/proto/proto_pb2_twirp.py, internal/twirptest/service_pb2_twirp.py, protoc-gen-twirp_python/main.go
- Use standard Exception super().\_\_init\_\_() to give TwirpExceptions a
message so that they print out more useful information in a backtrace.
- Update all generated python files appropriately.
=> Make Python TwirpExceptions better behaved.

README.md
@cyrusaf and me have the Ruby `twirp` gem up and running, currently at version `v0.1.0` (feature complete for the service, but not tested in production yet).
The package `twirp/error` defines the `Twirp::Error` class. This will be used both by services and clients.
The package `twirp/service` allows to use the service DSL to define services from existing Protobuf message classes:
```ruby
class Haberdasher < Twirp::Service
rpc :MakeHat, Size, Hat, :handler_method => :make_hat
end
```
The service is implemented with a handler, for example:
```ruby
class HaberdasherHandler
def make_hat(size)
{size: size, name: "Hat"}
end
end
```
And then mounted as a Rack app, with optional …
=> Add reference to Twirp Ruby services

README.md
Added entry for typescript twirp client protoc plugin.
Closes Issue #93 
Added a link to the typescript client protoc plugin I created.
=> Add typescript client protoc plugin to README.md

README.md
Just released ruby-twirp 0.2.0 that implements [Twirp::Client](https://github.com/cyrusaf/ruby-twirp/pull/5). It is fully functional for proto requests.
The implementation for `Twirp::Client` uses `Twirp::Error` just like `Twirp::Service`. I think at this point we should recommend using this Twirp instead of `github.com/gaffneyc/protoc-gen-twirp_ruby` that generates a client that is not compatible with the error in here. But please LMK if you want to keep that project in the list as well and I'll add it back.
=> Ruby Twirp now supports clients as well

clientcompat/internal/clientcompat/clientcompat.twirp.go, clientcompat/pycompat/clientcompat_pb2_twirp.py, example/service.twirp.go, example/service_pb2_twirp.py, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importable/importable_pb2_twirp.py, internal/twirptest/importer/importer.twirp.go, internal/twirptest/importer/importer_pb2_twirp.py, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/multiple/multiple1_pb2_twirp.py, internal/twirptest/multiple/multiple2.twirp.go, internal/twirptest/multiple/multiple2_pb2_twirp.py, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name/no_package_name_pb2_twirp.py, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer_pb2_twirp.py, internal/twirptest/proto/proto.twirp.go, internal/twirptest/proto/proto_pb2_twirp.py, internal/twirptest/service.twirp.go, internal/twirptest/service_pb2_twirp.py, protoc-gen-twirp/generator.go, protoc-gen-twirp_python/main.go
#86 
This change implements the plan discussed in #86: It removes the /twirp prefix from routes.
This would be merged into a 'v6_prerelease' branch, not master.
=> Remove /twirp prefix from routes

README.md
The Ruby implementation has been moved to `twitchtv/twirp-ruby`. This updates the reference.
=> Update reference to the twirp-ruby repository

clientcompat/internal/clientcompat/clientcompat.twirp.go, example/service.twirp.go, internal/twirptest/client_test.go, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/importmapping/x/x.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/multiple/multiple2.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, protoc-gen-twirp/generator.go
Currently when the service returns `nil, err`, the client is returning `new(Message), err`. This can be confusing when handling errors in the client code, where the response is expected to be nil instead of a pointer to a zero-values-struct.
Since the Twirp wire protocol does not allow to send partial-responses with errors at the same time, the easy fix is to just return `nil` in the client if there's an error.
*Warning*: The zero-value-struct will be replaced for `nil`. This means that if any code was wrongly accessing the zero-value-struct on errors it will now panic.
---
=> Nil responses on errors

docs/curl.md, docs/protobuf_and_json.md, website/sidebars.json
What
===
Add doc page with a cURL exaple.
Why
===
cURLing is an important part of being able to debug a service. It's
worth providing examples using JSON and Protobufs as it can be daunting
figuring out how to do both correctly.
Resolves #22
=> Add doc page with a cURL example

protoc-gen-twirp/command_line.go, protoc-gen-twirp/generator.go, protoc-gen-twirp/go_naming.go
Previously, specifying the option go_package caused the generator
to write a file to the fully qualified path
This would create the full directory tree
this doesn't really work as it adds, to your project root dir, the full github.com/blah/...
structure
This change does two things
adds support for the `paths=source_relative` like the google protoc plugin does
which ensures we write to whatever directory the .proto file lives in
secondly, it makes sure to use whatever go_package says when importing the module.
It was generating imports with relative dirs from the project root
With these two changes, you can use twirp with go 1.11's modules now
=> Improve support for go_package option in .proto files

README.md
Resolves #136 
Adds Dart client to README.md
=> adding Dart client to readme

errors.go
Just fixing this little syntax error in the documentation... 🙂
=> Fix code syntax in documentation example

requirements.txt
Python requests below 2.20.0 are impacted by CVE-2018-18074. This updates requests to a more recent version not impacted by this CVE.
Signed-off-by: Nicole Renée Hubbard <nicole@nicolerenee.io>
=> Update python requests

internal/gen/main.go
Fix `readGenRequest` to read `plugin.CodeGeneratorRequest` from `io.Reader` not from `os.Stdin`.
=> Fix readGenRequest to read request from io.Reader

.gitignore, CONTRIBUTING.md, Makefile, internal/release_gen.sh
Fixes #152 assuming the next release includes the generated binaries and sha256sum files.
This adds a script to generate release assets for Twirp. The script `internal/release_gen.sh` generates a binary for each of Darwin/Linux in x86_64 along with a sha256sum file, and then verifies the sha256sum. It does this in a platform-independent manner.
The Makefile target `release_gen` calls `git clean xdf` to make the repository pristine (not strictly necessary, but not a bad practice overall), and calls this script inside a Docker container, both to make sure no external dependencies are being used, and to make sure that if either binary panics, the file paths are printed out as `/go/src/...` not `/Users/whoever/go/src` etc.
It would be best to get #153 merged first as this makes the most sense …
=> Add release generation process

example/cmd/server/main.go
The example uses rand.Intn(4) on a slice of len 5, meaning the last element (e.g. "blue") can never be returned. rand.Intn should be called with the len of the slice.
=> Fix use of rand.Intn

hooks/statsd/statsd.go
The comment outlining the statsd metrics emitted by twirp uses 'by_code'
The actual metrics sent use 'status_codes' in place of 'by_code'.
This commit resolves that discrepancy.
Fixes #190 
=> hooks/statsd: update statsd docs to reflect current state of code

docs/errors.md, errors.go
Fixes #186 #161 
This changeset copies the twirp service implementation of `WriteError` to the core `twitchtv/twirp` package. 
Note, all mention of "hooks" and underlying use of context has been removed. 
---
=> Adds WriteError func for writing Twirp errors to http.ResponseWriter

errors.go, errors_test.go, internal/gen/wrappers.go
https://github.com/twitchtv/twirp/issues/201
`WriteError` now returns the error it might encounter while writing.
Added tests to cover `WriteError`'s happy path and error case.
<hr>
=> Return error from WriteError

protoc-gen-twirp/generator.go
Due to some extension used in my *.proto files I have following alias in the generated code:
```go
import http1 "net/http"
```
Compiler gives me the following error:
```
service.twirp.go:1023:80: undefined: http
```
=> Fixed package alias for net/http

clientcompat/internal/clientcompat/clientcompat.twirp.go, example/service.twirp.go, internal/twirptest/empty_service/empty_service.twirp.go, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/google_protobuf_imports/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/importmapping/x/x.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, internal/twirptest/service_method_same_name/service_method_same_name.twirp.go, internal/twirptest/snake_case_names/snake_case_names.twirp.go, internal/twirptest/source_relative/source_relative.twirp.go, protoc-gen-twirp/generator.go
Fixes https://github.com/twitchtv/twirp/issues/233
This adds the "body" metadata to the response when the err code is missing or invalid
I have updated `generator.go` and ran `retool do go generate ./...` -- hopefully this was the correct process. But definitely let me know if I need to do anything different. 
=> Include response body in metadata when server returns invalid code

context.go, docs/headers.md, internal/twirptest/service_test.go
Hi! I always use your wonderful library `twirp`.
I'd like to set multiple variables to the response header in the same key.
So I replaces `responseWriter.Header().Set()` with `responseWriter.Header().Add()`.
=> AddHTTPResponseHeader to allow responseWriter.Header().Add() in addition to Set

errors.go, errors_test.go
And support the Unwrap() method in addition to Cause()
Issue #228 
Add a function `WrapError(ErrorCode, error) Error`, which allows wrapping an error with any error code, not just Internal errors.
And add the `Unwrap()` method to the `wrappedErr` type, to be compatible with Go 1.13's new error unwrapping.
=> Allow wrapping any error code, not just Internal errors

README.md
Twinagle is an implementation of the Twirp protocol for Scala/Finagle.
It is used in production at SoundCloud, and we just [announced](https://developers.soundcloud.com/blog/announcing-twinagle) the OSS release today (though the code has been in the open for a while already).
=> add Twinagle to list of Twirp implementations

README.md
Thanks for putting all the work into this. I just wanted to add our elixir implementation to the list.
=> Add elixir to third party implementations list

docs/routing.md
Names are actually `snake_case`.
As per issue: https://github.com/twitchtv/twirp/issues/84
=> Correct docs relating to JSON serialization.

clientcompat/internal/clientcompat/clientcompat.twirp.go, example/service.twirp.go, internal/twirptest/empty_service/empty_service.twirp.go, internal/twirptest/gogo_compat/service.twirp.go, internal/twirptest/google_protobuf_imports/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/importer_local/importer_local.twirp.go, internal/twirptest/importmapping/x/x.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/multiple/multiple2.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/proto/proto.twirp.go, internal/twirptest/service.twirp.go, internal/twirptest/service_method_same_name/service_method_same_name.twirp.go, internal/twirptest/snake_case_names/snake_case_names.twirp.go, internal/twirptest/source_relative/source_relative.twirp.go, protoc-gen-twirp/generator.go, version_constant.go
The PR #264 includes new server options in the `twirp` package that are used by the generated code. If the `protoc-gen-twirp` plugin used to generate code uses the latest version, but the `twirp` package in the project is an older version, the generated code will fail with a compile-time error. Without this constant, the error is something like `clientOpts.PathPrefix() function does not exist`. With this constant, the error is more descriptive, like `twirp.TwirpPackageIsVersion7 does not exist`, which better points to the solution.
This pattern is similar to protobuf generated code, that uses compile-time assertions like `proto.ProtoPackageIsVersion4` to make sure the right version of the proto library is included in the destination project.
By submitting this pull request, I confirm that …
=> Add version_constant and check from generated code

.github/stale.yaml
This is a follow-up to #283 to correct the message that gets posted in stale issues and PRs to reflect the 60-day stale period.
=> Match stale-xyz-message with days-before-stale

protoc-gen-twirp/go_naming.go, protoc-gen-twirp/go_naming_test.go
This PR adds a new check to the `go_option` parser to see if it includes a semi-colon. If it does, that means the user has already provided both the import path as well as the package name and that Twirp shouldn't try to deduce either of them. 
In protobuf-go's v2, this is going to be the new default. See the referenced issue for more details. 
Fixes https://github.com/twitchtv/twirp/issues/280
=> Fix go_option that contains both path and pkg

docs/example.md
By following the example, you run into this issue. 
This PR fixes this w/ relative path tweak suggested here: https://github.com/techschool/pcbook-go/issues/3
=> Make example work

clientcompat/main.go
reflect.DeepEqual() does not work as expected anymore with APIV2, see #310 for details.
Using proto.Equal() instead.
fixes #310
=> Fix clientcompat for APIV2

protoc-gen-twirp/generator.go
https://github.com/twitchtv/twirp/issues/298
Before writing out package names, append them to a slice and sort them.
This keeps the import list remaining in the same order. Otherwise, the generated protobuf `*.go` files may change even though `*.proto` is the same, which causes trouble in our CI environment.
I'm having trouble coming up with a test for this change. Any example I could look at?
=> Make sure import list is ordered

README.md
Greetings!
This PR adds the link of the Twirp Server & Client implementation in Typescript that we use at Hopin.
Hope you enjoy it!
Link:  https://github.com/hopin-team/twirp-ts
=> Typescript Twirp implementation link

protoc-gen-twirp/generator.go
Protobuf recently added support for [field presence][]. In a proto file, they are denoted by the `optional` keyword, e.g.
```proto
message Foo {
optional string bar = 1;
}
```
Support for optional fields is opt-in on a per-code-generator basis. Without adding a particular flag, you get an error:
example.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-twirp hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
As far as I can tell, there should not be anything special we need to do to support optional fields in Twirp as we only reference message types and don't do anything with their fields.
Support was previously attempted in https://github.com/twitchtv/twirp/pull/275 but that …
=> Support proto3 field presence

errors.go, errors_test.go
The standard error constructor `twirp.NewError(twirp.ErrorCode, msg)` stutters and is a bit verbose.
Since the code constants are already defined at the top level of the twirp package, they can be used to build all the error types. It is easier to read and consistent for all codes:
```go
twirp.Internal.Error("oops")
twirp.NotFound.Error("resource not found")
twirp.PermissionDenied.Error("thou shall no pass")
```
The signature `Errorf` is a well-known idiom in Go and could be used to format errors exactly as it would be expected:
```go
twirp.Internal.Errorf("oops: %w", err) // wrapping another error
twirp.NotFound.Errorf("resource with id: %d", id) // interpolation
twirp.PermissionDenied.Errorf("user %q with id %d not allowed: %w", login, id, err) // all of the above
```
Wrapping errors …
=> New Error Constructors: code.Error(msg) and code.Errorf(msg, a...)

docs/install.md
The installation guide in the docs uses a slightly outdated `go install` command as this now requires a version to install (e.g. `@latest`) as the suffix.
This is a small change to add this `latest` version info.
=> Docs: Fix installation commands

README.md
Add github.com/timostamm/protobuf-ts as a Typescript implementation of Twirp.
=> Add timostamm/protobuf-ts to implementations

docs/best_practices.md
#348 
This pull request fixes the problem when generating the `best practices` page in the documentation. For this, just change the quotes in the page's markdown metadata.
=> Fix generation of the best practices page

protoc-gen-twirp/go_naming.go, protoc-gen-twirp/go_naming_test.go
Closes https://github.com/twitchtv/twirp/issues/350
=> Fix generated file name error in some cases

docs/routing.md, errors.go
Just noticed looking at the docs that according to the routing section errors have a "type" field, but everywhere else this field is called "code" (I guess it was "type" in a previous version).
=> Replace references to Error type with Error code

docs/errors.md, website/i18n/en.json
Update docs for Twirp Errors:
* Organize for better readability: Overview; Error codes; Server side; Client side; Metadata.
* Update examples using new error constructors and idioms.
* Show common error codes first, and include a link to see all other codes in the spec.
* Improve links to source code on relevant examples.
* Explain how vanilla (non-twirp) errors are wrapped as internal errors with more detail.
=> Update docs for Twirp Errors

README.md
I no longer maintain this library, and have archived the repo. It should no longer be listed as a Typescript integration for Twirp.
=> Remove protoc-gen-twirp_typescript from README

README.md
This is the current fork, the other one has been abandoned
=> Update prost-twirp link

docs/example.md
Running the command in the example documentation results in the error `paths=./: No such file or directory`. This changes the arguments to be the same as other commands elsewhere in the documentation.
=> Fix example protoc arguments

website/static/.well-known/assetlinks.json
*Issue:* #390 
Following google's instructions here: https://chromium.googlesource.com/chromium/src/+/master/docs/security/lookalikes/lookalike-domains.md#Removing-Lookalike-Warnings-from-a-site
I know it says not to use subdomains, but I figure because the error itself only presents on the specific subdomain, that maybe we can get away with only specifying the subdomain. We can update this later to github.io if needed.
The same change needs to be made against twitch.tv, which I'll work to have done internally.
=> add .well-known to static directory to resolve automated lookalike warning
