.github/PULL_REQUEST_TEMPLATE.md, LICENSE, NOTICE, README.md
Adding missing files; fixing license to be standard; adding license to readme
=> License fixes

THIRD_PARTY
Adding a third party license file to show the other licensing inside the project
=> Adding a third party license file

docs/errors.md, docs/protobuf_and_json.md
Also change one instance of Golang to Go.
=> Fix typos in docs

README.md
Though it's still WIP, it already has a pre-release.
=> Add PHP library to the readme

README.md
Added a link to a java server implementation
=> Added link to java server implementation

docs/example.md
=> Fixed missing fmt import

README.md
https://github.com/fajran/protoc-gen-twirp_java_jaxrs/pull/5 added server functionality.
=> readme: java_jaxrs add server functionality

requirements.txt
updated urllib3 verision in requirements.txt, ran tests
=> update urllib3 version for CVE-2018-20060

clientcompat/pycompat/clientcompat_pb2.py, example/service_pb2.py, internal/twirptest/google_protobuf_imports/service_pb2.py, internal/twirptest/importable/importable_pb2.py, internal/twirptest/importer/importer_pb2.py, internal/twirptest/importmapping/x/x_pb2.py, internal/twirptest/importmapping/y/y_pb2.py, internal/twirptest/multiple/multiple1_pb2.py, internal/twirptest/multiple/multiple2_pb2.py, internal/twirptest/no_package_name/no_package_name_pb2.py, internal/twirptest/no_package_name_importer/no_package_name_importer_pb2.py, internal/twirptest/proto/proto_pb2.py, internal/twirptest/service_method_same_name/service_method_same_name_pb2.py, internal/twirptest/service_pb2.py, internal/twirptest/snake_case_names/snake_case_names_pb2.py, internal/twirptest/source_relative/source_relative_pb2.py
Running `make test_core` in my machine updates some files. To keep branch development clean, we should commit this differences first.
=> Run make test_core

README.md, errors_test.go
#185 , #220 
- Clarifies state of go, python client and server codegen support in official repo
- Adds [twirpy](https://github.com/verloop/twirpy) for python3
- Completes an [old promise](https://github.com/twitchtv/twirp/pull/208#discussion_r359831855)
=> Clarify generator language server and client support, add twirpy

CONTRIBUTING.md, docs/headers.md, website/i18n/en.json
Minor documentation changes in `CONTRIBUTING.md` regarding making changes to the documentation website.
=> update docs workflow in CONTRIBUTING.md

docs/intro.md
Issue #266
Include a link from the docs to the Github page.
=> Include link to the Github site

interceptors.go, internal/twirptest/json_serialization/json_serialization_test.go, internal/twirptest/service_test.go, vendor_test.go
=> fix misspells

.github/stale.yaml
There are some issues and PRs that have been not active on the repo for a while and look to have been abandoned by their original creators. Please accept this PR so that github actions can handle dealing with stale PRs and issues.
=> Added Stale issues and PRs GitHub action

.github/workflows/commit-checks.yml, .github/workflows/pr-checks.yml
Adds test checks on commits and code coverage requirement for PRs.
=> GitHub Actions for Code Coverage and Testing

.github/workflows/stale.yaml
Configure the stale closer to skip issues and PRs with the pending label.
=> add stale exemption label to stale closer config

README.md
*Description of changes:* TwirpScript is a new TypeScript implementation
=> Add TwirpScript

README.md
https://github.com/CrazyHulk/protoc-gen-swiftwirp now support swift
client, and server in progress.
=> add swift client support link

docs/example.md
Latest index is not generated by random any time.
=> Update Example Documentation, fix random size in *Implement the Server*

README.md
=> Make README third-party table consistent

example/service.twirp.go, protoc-gen-twirp/generator.go
Fixed spelling error brought up by cSpell
=> Fixed spelling error.

protoc-gen-twirp/generator.go
=> Spelling fix

README.md
=> Add link to crystal implementation

README.md
Add link to https://github.com/collectiveidea/twirp-kmm for Kotlin Multiplatform Mobile client-side Twirp integration.
=> Update README.md for Kotlin Multiplatform Mobile client-side Twirp integration.

docs/headers.md
*Issue #, if available:* n/a
*Description of changes:* typo in markdown styling
=> Fix typo headers.md

clientcompat/internal/clientcompat/clientcompat.twirp.go, example/service.twirp.go, internal/twirptest/empty_service/empty_service.twirp.go, internal/twirptest/google_protobuf_imports/service.twirp.go, internal/twirptest/importable/importable.twirp.go, internal/twirptest/importer/importer.twirp.go, internal/twirptest/importer_local/importer_local.twirp.go, internal/twirptest/importmapping/x/x.twirp.go, internal/twirptest/json_serialization/json_serialization.twirp.go, internal/twirptest/multiple/multiple1.twirp.go, internal/twirptest/no_package_name/no_package_name.twirp.go, internal/twirptest/no_package_name_importer/no_package_name_importer.twirp.go, internal/twirptest/service.twirp.go, internal/twirptest/service_method_same_name/service_method_same_name.twirp.go, internal/twirptest/snake_case_names/snake_case_names.twirp.go, protoc-gen-twirp/generator.go
=> chore: remove repetitive words
